pipeline {
    agent any

    tools {
        // Must match the exact name configured in Jenkins UI
        maven 'Maven-3' 
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'master', url: 'https://github.com/ShaktiDevOps/devops-practice.git'
            }
        }

        stage('Build') {
            steps {
                dir('a2345') {
                    sh 'mvn clean package'
                }
            }
        }

        stage('Docker Build') {
            steps {
                dir('a2345') {
                    sh 'docker build -t demo-app:v1 .'
                }
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}
